### ISSUE TITLE
Failed to connect to duckling http server on windows

### ISSUE THREAD

**Issue by ermarkar** [facebook/duckling#586]
I am using DucklingHTTPExtractor in rasa pipeline

```
- name: DucklingHTTPExtractor
  dimensions:
  - time
  - interval
  - duration
  - email
  - number
  - phone-number
  timezone: Central European
  url: http://localhost:8000
```

so i satrted duckling serer on my local machine. and on hit of http://localhost:8000 it shows quack

but when i run rasa x

it shows 

`Failed to connect to duckling http server. Make sure the duckling server is running/healthy/not stale and the proper host and port are set in the configuration. More information on how to run the server can be found on github: https://github.com/facebook/duckling#quickstart Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

Am i missing something?
